services:
  postgres_db:
    image: postgres:15-alpine
    container_name: lattic_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
  
  redis_server:
     image: redis:7-alpine
     container_name: lattic_redis
     restart: always
     networks:
       - backend_network
     healthcheck:
       test: ["CMD", "redis-cli", "ping"]
       interval: 3s
       timeout: 3s
       retries: 5
  
  backend:
    build: .
    container_name: lattic_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - bill_uploads:/data/uploads
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_started
      redis_server:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - backend_network

  worker:
    build: .
    container_name: lattic_worker
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/app
      - bill_uploads:/data/uploads
    env_file: 
      - .env
    depends_on:
      postgres_db:
        condition: service_started
      redis_server:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - backend_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_storage:/root/.ollama
    restart: always
    networks:
      - backend_network

volumes:
  postgres_data:
  ollama_storage:
  shared_uploads:
  bill_uploads:

networks:
  backend_network:
    driver: bridge
    name: backend_network
    
